### ISSUE TITLE
Crashing renderer when added

### ISSUE THREAD

**Issue by mcerignoni** [quentin452/ArchaicFix#5]
[crash-2024-02-03_12.06.43-client.txt](https://github.com/quentin452/ArchaicFix/files/14151902/crash-2024-02-03_12.06.43-client.txt)

Tried downloading the latest release to run with OptimizationsAndTweaks but with no luck.

**Comment by quentin452** [comment]
it seem that you had threaded /occlusion things from falsetweaks enabled with archaicfix

Falsetweaks threaded chunk updates/occlsuion things are not compatible with Archaicfix threaded chunk updates/occlsuion things

**Comment by mcerignoni** [comment]
It works! Got the impression I might have overlooked that somewhere... Anyway thank you for your help!
